<a href="https://colab.research.google.com/github/Ragulan-K/LLM-/blob/main/1_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [9]:
from numpy import array #For array Initialization
from numpy import random #For Randomly choosing numbers
from numpy import dot #For doing dot product
from random import choice

#Activation Function

In [2]:
activationFn = lambda x: 0 if x<0 else 1 #Step activation function (if i/p is negative o/p is 0)

#Initializing dataset

In [4]:
dataset=[
    (array([0,0,1]),0),   #array([x,y,b],e) x,y=Input , b=bias ,e=Expected O/P to validate
    (array([0,1,1]),1),
    (array([1,0,1]),1),
    (array([1,1,1]),1),

]
print(dataset)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]


#Initializing Random numbers for Weights

In [7]:
weights=random.rand(3)
weights

array([0.13475565, 0.23377467, 0.67224098])

#Initializing additional variables

In [8]:
r=0.2 #Learning rate
n=100 #Number of iteration

#Training the model

In [10]:
for j in range(n):
  x,expected=choice(dataset) #random input set,Includes repeated numbers
  #print(x,expected)
  result=dot(weights,x) #dot product of the input and the weight vectors
  err=expected-activationFn(result)
  weights+=r*err*x #calculate the correction factor, added to weights to improve o/p in next iteration
  #if the expected value is bigger , the weights should be increased, and if expected value is smaller ,the weights should be decreased

#Evaluating Model

In [11]:
for x,_ in dataset:
  result=dot(x,weights)
  print("Input:{} ResultBAFn:{} ResultAFn:{}".format(x[:2],round(result,3),activationFn(result)))

Input:[0 0] ResultBAFn:-0.128 ResultAFn:0
Input:[0 1] ResultBAFn:0.106 ResultAFn:1
Input:[1 0] ResultBAFn:0.007 ResultAFn:1
Input:[1 1] ResultBAFn:0.241 ResultAFn:1
